<?php

if (WPLANG === 'nl_NL') {
    ?>
    <p>
        In dit gedeelte is het mogelijk je eigen shortcodes aan te maken. Je geeft aan elke shortcode een collectie, een label en een waarde.<br/> 
        Een voorbeeld is: <code>collectie="adres", label="straat", waarde="Sesamstraat"</code>. Het genoemde voorbeeld kun je vervolgens aanroepen in pagina's, berichten en commentaar met de shortcode: <code>[audax_custom adres="straat"]</code>. <br/>
        Klinkt eenvoudig toch? Dit voorbeeld beperkt zich tot adresgegevens maar je zou hier natuurlijk ook product prijzen in kunnen vullen of een standaard voetregel die onderaan iedere pagina moet verschijnen. <br/>
        <br/>
        Om de regels aan te passen klik je op de <span class="audax-input-show">gemarkeerde</span> tekst en om een nieuwe regel aan te makken klik je onderaan op de knop "Nieuw".<br/>
        <br/><strong>Probeer het uit, je bent zo vrij als een vogel!</strong>
    </p>
    <?php

} else {
    ?>
    <p>
        In this section you can create your own shortcodes. You give each shortcode a collection, a label and a value. 
        For example: <code>collection = "address" label = "street" value = "Sesame Street"</code>.
        You can call the example mentioned in pages, posts and comments with the shortcode: <code>[audax_custom address = "street"]</code>.<br/>
        Sounds simple right? This example is limited to an address but you could also set product prices or a standard footer to appear at the bottom of each page. <br/>
        <br/>
        To edit the rules, click on the <span class="audax-input-show">highlighted</span> text and to add a new line to the bottom smacking click the "New" button.<br/>
        <br/><strong>Try it out, you're free as a bird!</strong>
    </p>
    <?php

}